### ISSUE TITLE
`url` interaction with redirects

### ISSUE THREAD

**Issue by axion014** [06chaynes/http-cache#1]
In `reqwest-middleware-cache` I added `url` to store which is supposed to store response URL, but this implementation seems to be storing request URL. The two can differ when the HTTP client is following redirects(it's the whole point of storing URL in cache).

In `reqwest`, redirect handling is baked into its core, and response URL can be retrieved from its `Response` object. In `surf` however, redirect handling is a middleware. I believe the consequence is that cache behavior would change depending on register order of middlewares, though I haven't tested it. It's not ideal, but I'm not sure if it can be fixed...

**Comment by 06chaynes** [comment]
I'll make that change for reqwest, just an error on my part when I was moving the code over.

I didn't consider how surf middleware order may impact things but that makes sense. I'll try testing a bit with that use case.

Maybe I should wrap the url field in HttpResponse with an Option? Then surf can use None rather than the request url to help avoid confusion.

**Comment by 06chaynes** [comment]
Just added the fix for this, for now Surf will continue to use the request url unless something can be worked out later.

**Comment by 06chaynes** [comment]
Also updated the readme on surf middleware order, would still like to test more but thought it was worth adding a note
