### ISSUE TITLE
Information about cache hits

### ISSUE THREAD

**Issue by stoically** [06chaynes/http-cache#10]
In my use case it'd be useful to have the information whether a request hit the cache or was sent to the server. Is it possible to get that info?

Thanks for a useful caching implementation!

**Comment by 06chaynes** [comment]
Started working on an implementation here: https://github.com/06chaynes/http-cache/blob/x-cache-headers/http-cache/src/lib.rs

**Comment by 06chaynes** [comment]
For quick reference what I have atm is:

`x-cache` header: Did this proxy serve the result from cache (HIT for yes, MISS for no)

`x-cache-lookup` header: Did the proxy have a cacheable response to the request (HIT for yes, MISS for no)

**Comment by stoically** [comment]
That's great. Exposing it as headers does indeed make sense. I wonder, does your branch also consider the case were your request contains the cache bypassing headers as mentioned in the blog article? Can't seem to see it. Just asking since if it doesn't, then `x-cache-lookup` wouldn't serve a purpose, right?

**Comment by 06chaynes** [comment]
I added this in somewhat hastily but I think I have the various situations covered in the logic. I did extend a few tests, including one to check for this particular situation. That test can be found here: https://github.com/06chaynes/http-cache/blob/668e42bce73dcf3a6a20d0fe58eab7799fd65db6/http-cache-tests/src/client_surf.rs#L104-141

I do a cold pass, check to make sure both headers were MISS, then a hot pass to make sure the lookup was a HIT but the return was a MISS (as I am forcing the NoCache mode in this test)

**Comment by 06chaynes** [comment]
The good news this has led to several bug fixes, the bad news is this has led to several bug fixes

For one it turns out I wasn't properly handling a situation where the conditional response was a 200, and was returning the cached response instead. This meant that I wasn't properly respecting the no-cache directive in the response. I think I have that fixed now though, at least my test seem to be giving the expected output for this scenario.

**Comment by 06chaynes** [comment]
Dang I had a lot more wrong than I had realized, fun times. Anyways I think what I have now is really close, and the amount of logic issues this helped find was worth it alone. Sometimes you just need some tedious (but valuable) tests to tell you what's up (let's hope those are correct as well!)

**Comment by 06chaynes** [comment]
Since I include the method as part of the cached record’s key (“<method>:<url>”) the responses for GET and HEAD requests are stored separately and both should be subject to the same set of rules.

So the first HEAD and GET requests to a resource should result in two requests, while subsequent requests would follow the revalidation logic each with their own policy. So if the next HEAD request is made and the cached record is fresh it shouldn’t result in a request, unless revalidation was determined to be required whereas a revalidation request would be sent. 

So you could potentially have a revalidation request sent for both depending on the directives, cache mode, age, etc. I don’t think it would result in a third request though because if the server determines the response to be stale it should return the new body with a 200 status, which would update the record in cache for that method-resource combo and return the new response.

I think this is the case anyways!

**Comment by stoically** [comment]
That confirmed again that caching is a beast. :sweat_smile: You seem to be right tho, I'm running a test against a wiremock server and it only sees two requests for my scenario. So all seems fine and the issue could be closed from my perspective. :+1:

**Comment by 06chaynes** [comment]
Good to hear! I should have a new version published sometime today. The bump of http-cache-semantics to v1.0.0 also bumped the MSRV up to 1.56.1, so considering if I should go ahead and change editions before I publish since that's the case.

**Comment by 06chaynes** [comment]
Fixed in PR #11
