### ISSUE TITLE
`Cache-Control: no-cache` header on request not respected?

### ISSUE THREAD

**Issue by nokome** [06chaynes/http-cache#13]
First, thanks for `http-cache` 🙏🏽 , I'm using it in various places in [Stencila](https://github.com/stencila/stencila) and it's been working great!

I'm currently using it as part of our Docker / OCI integration. I am finding that it is caching response despite the `Cache-Control: no-cache` header being set on the request (note `"x-cache-lookup": "HIT"` below. Is this intended or am I doing something wrong or misinterpreting the standard?

```rs
       let response = self
            .get(["/blobs/", digest].concat())
            .header("Cache-Control", "no-cache")
            .send()
            .await?;
        println!("{:#?}", response);
```

```js
Response {
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "localhost",
            ),
        ),
        port: Some(
            5000,
        ),
        path: "/v2/test/blobs/sha256:125a6e411906fe6b0aaa50fc9d600bf6ff9bb11a8651727ce1ed482dc271c24c",
        query: None,
        fragment: None,
    },
    status: 200,
    headers: {
        "docker-content-digest": "sha256:125a6e411906fe6b0aaa50fc9d600bf6ff9bb11a8651727ce1ed482dc271c24c",
        "x-content-type-options": "nosniff",
        "x-cache": "HIT",
        "x-cache-lookup": "HIT",
        "content-length": "30421006",
        "content-type": "application/octet-stream",
        "docker-distribution-api-version": "registry/2.0",
        "etag": "\"sha256:125a6e411906fe6b0aaa50fc9d600bf6ff9bb11a8651727ce1ed482dc271c24c\"",
        "accept-ranges": "bytes",
        "date": "Sun, 29 May 2022 22:08:28 +0000",
        "cache-control": "max-age=31536000",
        "age": "0",
    },
}
```

I can add a random `?cache-buster=` to the URL to work around it but that feels a it hackish.

**Comment by 06chaynes** [comment]
Very cool to hear, thanks for sharing!

So this one confused me as well at first. This really comes from the cache header directive, which in my opinion was poorly named because I would expect 'no-cache' to literally mean do not cache this. But it actually is more of a, cache this but force a validation before responding with it. 

Here's the relevant portion from the docs:
`The no-cache response directive indicates that the response can be stored in caches, but the response must be validated with the origin server before each reuse, even when the cache is disconnected from the origin server.` [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)

The directive that tells the client not to cache at all is named 'no-store'. Not confusing at all right! 😀 

I considered having the cache modes differ from the spec in this regard, but decided that it could ultimately be more confusing to not have it match the directives seen in the headers. That said, I'm still open to reconsidering that decision.

**Comment by nokome** [comment]
Thanks very much for the quick and detailed response, appreciated. I'll try `no-store` then :)

**Comment by nokome** [comment]
Confirming that `no-store` gives expected behaviour. Will close this issue. Thanks again for your help.
